spring:
  application:
    name: binflare-plus
  profiles:
    active: dev

server:
  port: 9000

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_KEY}

mybatis:
  config-location: classpath:mybatis-config.xml
